<?php
// $Id: upei_footer.module,v 1.0 2012/09/26 11:09:08 krisbulman Exp $

/*
 * Implementation of hook_theme().
 */
function upei_footer_theme() {
  return array(
    'upei_footer_footer' => array('arguments' => array(), 'template' => 'upei-footer-footer')
  );
}

/*
 * Implementation of hook_block().
 */
function upei_footer_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      return array(
        0 => array(
          'info' => t('UPEI footer'),
        ),
     );
    case 'view':
      

$subject = '';
      $content = '';
      switch (

$delta) {
        case 0:
          $content = theme('upei_footer_footer');
          $subject = t('');
        break;
      } 
    if (

$subject || $content) {
      return array(
        'subject' => $subject,
        'content' => $content,
      );
    }
    break;
  }
}

function upei_footer_preprocess_upei_footer_footer($vars) {
  $request = drupal_http_request('http://www.upei.ca/becomeastudent/files/misc/footer.php');
  $data = $request->data;
  $request_code = $request->code;
  if ($request_code === "200") {
    $vars['external_php'] = $data;
  }
}
