<?php
// $Id: upei_footer.module,v 1.0 2012/09/26 11:09:08 krisbulman Exp $

/*
 * Implementation of hook_theme().
 */
function upei_footer_theme() {
  return array(
    'upei_footer_footer' => array('arguments' => array(), 'template' => 'upei-footer-footer')
  );
}

function upei_footer_block_info() {
  $blocks['upei_footer'] = array(
    'info' => t('UPEI footer'), //The name that will appear in the block list.
    'cache' => DRUPAL_CACHE_PER_ROLE, //Default
  );
  return $blocks;
}

function upei_footer_block_view($delta = '') {
  // This example is adapted from node.module.
  $block = array();

  switch ($delta) {
    case 0:
      $block['subject'] = t('');
      $block['content'] = array(
        '#theme' => 'upei_footer_footer', 
        '#url' => 'upei_footer_footer.tpl.php', 
        '#title' => t('UPEI footer'),
      );
    break;
  }

  return $block;
}

function upei_footer_preprocess_upei_footer_footer($vars) {
  $request = drupal_http_request('http://students.upei.ca/files/misc/footer.php');
  $data = $request->data;
  $request_code = $request->code;
  if ($request_code === "200") {
    $vars['external_php'] = $data;
  }
}
